<?php

namespace ContainerPGQr3nh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RoqezgmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Roqezgm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Roqezgm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sondageRepository' => ['privates', 'App\\Repository\\SondageRepository', 'getSondageRepositoryService', true],
        ], [
            'sondageRepository' => 'App\\Repository\\SondageRepository',
        ]);
    }
}
