<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0rfaK7K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0rfaK7K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0rfaK7K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0rfaK7K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0rfaK7K\App_KernelDevDebugContainer([
    'container.build_hash' => '0rfaK7K',
    'container.build_id' => '9c03ee2d',
    'container.build_time' => 1679487135,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0rfaK7K');
