<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQChbxDH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQChbxDH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQChbxDH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQChbxDH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQChbxDH\App_KernelDevDebugContainer([
    'container.build_hash' => 'QChbxDH',
    'container.build_id' => 'b916b50a',
    'container.build_time' => 1679413848,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQChbxDH');
