<?php

namespace Container1fsxXeX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pyf2GReService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Pyf2GRe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Pyf2GRe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'questionRepository' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
            'reponseRepository' => ['privates', 'App\\Repository\\ReponseRepository', 'getReponseRepositoryService', true],
            'sondage' => ['privates', '.errored..service_locator.Pyf2GRe.App\\Entity\\Sondage', NULL, 'Cannot autowire service ".service_locator.Pyf2GRe": it needs an instance of "App\\Entity\\Sondage" but this type has been excluded in "config/services.yaml".'],
            'sondageRepository' => ['privates', 'App\\Repository\\SondageRepository', 'getSondageRepositoryService', true],
            'typeRepository' => ['privates', 'App\\Repository\\TypeRepository', 'getTypeRepositoryService', true],
            'visuelRepository' => ['privates', 'App\\Repository\\VisuelRepository', 'getVisuelRepositoryService', true],
        ], [
            'questionRepository' => 'App\\Repository\\QuestionRepository',
            'reponseRepository' => 'App\\Repository\\ReponseRepository',
            'sondage' => 'App\\Entity\\Sondage',
            'sondageRepository' => 'App\\Repository\\SondageRepository',
            'typeRepository' => 'App\\Repository\\TypeRepository',
            'visuelRepository' => 'App\\Repository\\VisuelRepository',
        ]);
    }
}
