nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: ['http://127.0.0.1:3000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST']
            max_age: 3600
