<?php

namespace ContainerJhxLKeI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VuYSycTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vuYSycT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vuYSycT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'passwordHash' => ['privates', '.errored.OPtKNJv', NULL, 'Cannot determine controller argument for "App\\Controller\\RacineController::modifierInformation()": the $passwordHash argument is type-hinted with the non-existent class or interface: "App\\Controller\\UserPasswordHasherInterface". Did you forget to add a use statement?'],
            'utilisateurRepository' => ['privates', '.errored.oGklmZ5', NULL, 'Cannot determine controller argument for "App\\Controller\\RacineController::modifierInformation()": the $utilisateurRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\UtilisateurRepository". Did you forget to add a use statement?'],
        ], [
            'passwordHash' => '?',
            'utilisateurRepository' => '?',
        ]);
    }
}
