<?php

namespace ContainerKqIzwNa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MHJAWU7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mHJAWU7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mHJAWU7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'questionRepository' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
            'sondage' => ['privates', '.errored..service_locator.mHJAWU7.App\\Entity\\Sondage', NULL, 'Cannot autowire service ".service_locator.mHJAWU7": it needs an instance of "App\\Entity\\Sondage" but this type has been excluded in "config/services.yaml".'],
            'sondageRepository' => ['privates', 'App\\Repository\\SondageRepository', 'getSondageRepositoryService', true],
        ], [
            'questionRepository' => 'App\\Repository\\QuestionRepository',
            'sondage' => 'App\\Entity\\Sondage',
            'sondageRepository' => 'App\\Repository\\SondageRepository',
        ]);
    }
}
