<?php

namespace ContainerPEabcFV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSondage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iJVNhnm.App\Entity\Sondage' shared service.
     *
     * @return \App\Entity\Sondage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.iJVNhnm": it needs an instance of "App\\Entity\\Sondage" but this type has been excluded in "config/services.yaml".');
    }
}
